name: "CI: Build and Test"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  dotnet-format:
    name: .Net Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run dotnet format
        run: dotnet format Kentico.Xperience.RepoTemplate.sln --exclude ./examples/** --verify-no-changes

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: dotnet-format
    defaults:
      run:
        shell: pwsh

    env:
      ASPNETCORE_ENVIRONMENT: CI
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: |
          dotnet restore `
            --locked-mode

      - name: Build Solution
        run: |
          dotnet build `
            --configuration Release `
            --no-restore

      - name: Test Solution
        run: |
          dotnet test `
            --configuration Release `
            --no-build `
            --no-restore
